import profile_pfp from '../assets/profile_picture.jpeg'
import post_pic from '../assets/post-2.jpeg'
import post_pic2 from '../assets/post-1.jpeg'



const MyPosts = [
    {
        _id: 1,
        username: "Kurbonov Doniyorbek",
        user_img: profile_pfp,
        post_data: "1d",
        post_desc: `Salom !!!`,
        post_img: post_pic,
        comments: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        likes: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        shares: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        visible: true
    },
    {
        _id: 2,
        username: "Kurbonov Doniyorbek",
        user_img: profile_pfp,
        post_data: "6d",
        post_desc: `Hello World`,
        post_img: post_pic2,
        comments: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        likes: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        shares: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        visible: true
    }
]

export default MyPosts