const MyPosts = [
    {
        _id: 1,
        username: "Kurbonov Doniyorbek",
        user_img: "https://scontent.ftas2-2.fna.fbcdn.net/v/t39.30808-1/297874771_191457966651292_2308375852179335600_n.jpg?stp=dst-jpg_p480x480&_nc_cat=105&ccb=1-7&_nc_sid=7206a8&_nc_ohc=_rcyI3hFFjUAX84vPJG&_nc_ht=scontent.ftas2-2.fna&oh=00_AfAKXrY5vTbt7i-FgOYy3dH0W0nkqOq86ss4fPaa87YVFA&oe=64BC8098",
        post_data: "1d",
        post_desc: `Salom !!!`,
        post_img: "https://scontent.ftas1-1.fna.fbcdn.net/v/t39.30808-6/278170683_163001849496904_2278256263714684385_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=174925&_nc_ohc=UkMXFGJeBOEAX8-Z_Rq&_nc_ht=scontent.ftas1-1.fna&oh=00_AfDGLCGxXQe3msdCuH8GanD82mXKx9lGs4uerwCVmAhDyA&oe=64BD779B",
        comments: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        likes: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        shares: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        visible: true
    },
    {
        _id: 2,
        username: "Kurbonov Doniyorbek",
        user_img: "https://scontent.ftas2-2.fna.fbcdn.net/v/t39.30808-1/297874771_191457966651292_2308375852179335600_n.jpg?stp=dst-jpg_p480x480&_nc_cat=105&ccb=1-7&_nc_sid=7206a8&_nc_ohc=_rcyI3hFFjUAX84vPJG&_nc_ht=scontent.ftas2-2.fna&oh=00_AfAKXrY5vTbt7i-FgOYy3dH0W0nkqOq86ss4fPaa87YVFA&oe=64BC8098",
        post_data: "6d",
        post_desc: `Hello World`,
        post_img: "https://scontent.ftas2-2.fna.fbcdn.net/v/t39.30808-6/297874771_191457966651292_2308375852179335600_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=_rcyI3hFFjUAX84vPJG&_nc_ht=scontent.ftas2-2.fna&oh=00_AfAX8DrWD6xO9w3GoxT1YsWOg6npTpGgStZkLP0an2G3qg&oe=64BD54D2",
        comments: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        likes: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        shares: [
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
            "doniyor",
        ],
        visible: true
    }
]

export default MyPosts